services:
  bookdb:
    build: "."
    environment:
      - "ALLOW_WRITES=1"
      - "BASE_URI=http://localhost:8888"
      - "COVER_DIR=/covers"
      - "ES_HOST=http://elasticsearch:9200"
    networks:
      - "bookdb"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - "covers:/covers"

  elasticsearch:
    image: "elasticsearch:8.0.0"
    environment:
      - "ES_JAVA_OPTS=-Xms512M -Xmx512M"
      - "discovery.type=single-node"
      - "http.host=0.0.0.0"
      - "xpack.security.enabled=false"
    networks:
      - "bookdb"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"

networks:
  bookdb:

volumes:
  covers:
  esdata:
