mappings:
  properties:
    title:
      type: text
    subtitle:
      type: text
    volume_title:
      type: text
    display_title:
      type: text

    volume_number:
      type: object
      properties:
        raw:
          type: keyword
        # 'raw' split into numeric and non-numeric chunks
        bits:
          type: keyword

    fascicle_number:
      type: object
      properties:
        raw:
          type: keyword
        # 'raw' split into numeric and non-numeric chunks
        bits:
          type: keyword

    people:
      type: object
      dynamic: strict
      properties:
        authors:
          type: keyword
        translators:
          type: keyword
        editors:
          type: keyword

    has_been_read:
      type: boolean
    last_read_date:
      type: date
      format: yyyy-MM-dd

    # all entries with a cover image have this field set
    cover_image_mimetype:
      type: keyword

    # a holding is a single copy of a book
    holdings:
      type: nested
      dynamic: strict
      properties:
        location_uuid:
          type: keyword
        notes:
          type: text

    # case-insensitive bucket (usually first author surname) to use for sorting
    bucket:
      type: keyword

    category_uuid:
      type: keyword

    # metadata
    created_at:
      type: date
    updated_at:
      type: date
