name: Run tests

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup
        run: |
          set -ex
          python -m pip install --upgrade pip
          pip install flake8 black
      - name: Lint
        run: |
          set -ex
          flake8 --ignore=E266,E501 bookdb tests
          black -l200 bookdb tests
          git diff --exit-code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: snok/install-poetry@v1
      - name: Check Dependencies
        run: |
          set -ex
          poetry install --no-interaction
          poetry check
          poetry run pytest
