name: Run tests

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        run: rustup show

      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check flake.nix
        run: |
          set -ex
          nix flake check
          nix fmt
          git diff --exit-code

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Check clippy lints
        run: cargo clippy --tests -- -Dwarnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        run: rustup show

      - name: Run tests
        run: cargo test
