name: Run tests

on: pull_request

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: python
      - uses: github/codeql-action/analyze@v1

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Setup
        run: |
          set -ex
          python -m pip install --upgrade pip
          pip install flake8 black
      - name: Lint
        run: |
          set -ex
          flake8 --ignore=E266,E501 src
          black -l200 src
          git diff --exit-code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Check Dependencies
        run: |
          pip install -r requirements-freeze.txt
